from .modusponens import ModusPonens
from .modustollens import ModusTollens
from .hypotheticalsyllogism import HypotheticalSyllogism
from .disjunctivesyllogism import DisjunctiveSyllogism
from .biimplicationintroduction import BiimplicationIntroduction
from .biimplicationdissociation import BiimplicationDissociation
from .transposition import Transposition
from .associativity import Associativity
from .commutativity import Commutativity
from .distributivity import Distributivity
from .demorgan import DeMorgan
from .constructivedilemma import ConstructiveDilemma
from .exportation import Exportation
from .materialimplication import MaterialImplication
from .conjunction import Conjunction
from .simplification import Simplification
from .doublenegation import DoubleNegation